baseurl = "https://eliaslundgaard.com/"
languageCode = "en-US"
title = "Elias Lundgaard"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-WVSG0V1YJ0"
theme = "PaperMod"

[permalinks]
post = "/:year/:month/:day/:slug"

[params]
# Custom assets can be linked with their paths relative to static/
env = "production"
custom_css = ["css/styles.css", "css/header-overrides.css"]
custom_js = []
colorScheme = "dark"

math = true

[params.profileMode]
enabled = true

title = "Elias Lundgaard" # optional default will be site title
subtitle = "From Denmark, currently based in Reykjavik, Iceland. Founded an eye tracking company in 2017, and worked as CTO there until it's acquisition by [GN](https://www.gn.com) in 2021. Served as tech lead at [Jabra](https://www.jabra.com) until 2024. Now building [Wisp Compute](https://wispcompute.com)."
imageUrl = "avatar.jpg" # optional
imageTitle = "Avatar" # optional


[[params.socialIcons]] # optional
name = "github"
url = "https://github.com/gmcheese/"

[[params.socialIcons]] # optional
name = "linkedin"
url = "https://linkedin.com/in/eliaslundgaard"

[[params.socialIcons]] # optional
name = "email"
url = "mailto:web@eliaslundgaard.com"

## Main Menu
[[menu.main]]
name = "posts"
weight = 100
identifier = "posts"
url = "/posts/"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]